---
apiVersion: v1
kind: Pod
metadata:
  name: app-writer
  labels:
    app.kubernetes.io/name: app-writer
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v0.0.1
spec:
  volumes:
  # Определяем том и указываем, что он должен использовать PVC
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc-01
  containers:
  - name: writer
    image: busybox:1.37
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:  
    - |
      while true; do
        echo "Log entry at $(date)" >> /data/app.log;
        sleep 5;
      done;
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: nfs-storage
      mountPath: /data
