---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openresty-art.fullname" . }}-html
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.html }}
  {{ $name }}.html: |
{{ $content | indent 4 }}
{{- end }}