---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openresty-art.fullname" . }}
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
  {{- if .Values.application.reloader }}
  annotations:
    reloader.stakater.com/match: "true"
  {{- end }}
spec:
  selector:
    matchLabels:
      kubernetes.io/name: openresty-art
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        kubernetes.io/name: openresty-art
    spec:
      containers:
      - name: openresty-art
        image: openresty/openresty:1.27.1.2-0-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/openresty/nginx/html
        - name: conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html
        configMap:
          name: {{ include "openresty-art.fullname" . }}-html
      - name: conf
        configMap:
          name: {{ include "openresty-art.fullname" . }}-conf
