---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openresty-art.fullname" . }}
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
  {{- if .Values.application.reloader }}
  annotations:
    reloader.stakater.com/match: "true"
  {{- end }}
spec:
  replicas: {{ .Values.application.replicaCount }}
  revisionHistoryLimit: {{ .Values.application.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "openresty-art.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.application.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openresty-art.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "openresty-art.fullname" . }}
        image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.application.image.pullPolicy }}
        {{- with .Values.application.probes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.application.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 80
        {{- if .Values.application.volumeMounts }}
        volumeMounts:
          {{- toYaml .Values.application.volumeMounts | nindent 10 }}
        {{- end }}
      {{- if .Values.application.volumes }}
      volumes:
        {{- range .Values.application.volumes }}
        - name: {{ .name }}
          configMap:
            name: {{ printf "%s-%s" (include "openresty-art.fullname" $) .configMapSuffix }}
        {{- end }}
      {{- end }}
