---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openresty-art.fullname" . }}-svc
  labels:
    {{- include "openresty-art.labels" . | nindent 4 }}
spec:
  selector:
    kubernetes.io/name: openresty-art
  ports:
  - port: 80
    targetPort: 80
