---
# Source: openresty-art/templates/configmap-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: art-conf
  labels:
    helm.sh/chart: openresty-art-0.1.0
    app.kubernetes.io/name: openresty-art
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.27.1.2-0-alpine"
    app.kubernetes.io/managed-by: Helm
data:
  default.conf: |-
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/local/openresty/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/local/openresty/nginx/html;
        }
    }

---
# Source: openresty-art/templates/configmap-html.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: art-html
  labels:
    helm.sh/chart: openresty-art-0.1.0
    app.kubernetes.io/name: openresty-art
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.27.1.2-0-alpine"
    app.kubernetes.io/managed-by: Helm
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test page!</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>Test page!</h1>
    </body>
    </html>
  50x.html: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>50x error!</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>50x error!</h1>
    </body>
    </html>
---
# Source: openresty-art/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: art-svc
  labels:
    helm.sh/chart: openresty-art-0.1.0
    app.kubernetes.io/name: openresty-art
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.27.1.2-0-alpine"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    kubernetes.io/name: openresty-art
  ports:
  - port: 80
    targetPort: 80

---
# Source: openresty-art/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: art
  labels:
    helm.sh/chart: openresty-art-0.1.0
    app.kubernetes.io/name: openresty-art
    app.kubernetes.io/instance: app
    app.kubernetes.io/version: "1.27.1.2-0-alpine"
    app.kubernetes.io/managed-by: Helm
  annotations:
    reloader.stakater.com/match: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: openresty-art
      app.kubernetes.io/instance: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openresty-art
        app.kubernetes.io/instance: app
    spec:
      imagePullSecrets:
        - name: MySecret
      containers:
      - name: art
        image: "openresty/openresty:1.27.1.2-0-alpine"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/local/openresty/nginx/html
            name: html
          - mountPath: /etc/nginx/conf.d
            name: conf
      volumes:
        - name: html
          configMap:
            name: art-html
        - name: conf
          configMap:
            name: art-conf
