fullnameOverride: "art"

application:
  reloader: true
  podAnnotations: {}
  probes:
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3  
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumeMounts:
    - name: html
      mountPath: /usr/local/openresty/nginx/html
    - name: conf
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: html
      configMapSuffix: html
    - name: conf
      configMapSuffix: conf

service:
  # Service type: ClusterIP, NodePort.
  type: ClusterIP
  port: 80 
  name: "proxy"
  nodePort: ""
  targetPort: 80

httpRoute:
  # HTTPRoute enabled.
  enabled: true
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: cilium-gateway
    port: 80
    namespace: gateway-infra
  # Hostnames matching HTTP header.
  hostnames:
  - app.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /

conf:
  default: |
    server {
        listen 80;
        location / {
            root   /usr/local/openresty/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/openresty/nginx/html;
        }
    }

html:
  index: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test page!</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>Test page!</h1>
    </body>
    </html>
  50x: |-
    <!DOCTYPE html>
    <html>
    <head>
        <title>50x error!</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>50x error!</h1>
    </body>
    </html>