fullnameOverride: "art"

application:
  reloader: true
  podAnnotations: {}
  probes:
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3  
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  volumeMounts:
    - name: html
      mountPath: /usr/local/openresty/nginx/html
    - name: conf
      mountPath: /etc/nginx/conf.d
  volumes:
    - name: html
      configMapSuffix: html
    - name: conf
      configMapSuffix: conf

service:
  # Service type: ClusterIP, NodePort.
  type: ClusterIP
  port: 80 
  name: "proxy"
  nodePort: ""
  targetPort: 80

httpRoute:
  # HTTPRoute enabled.
  enabled: true
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: cilium-gateway
    port: 80
    namespace: gateway-infra
  # Hostnames matching HTTP header.
  hostnames:
  - app.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
