---
apiVersion: v1
kind: Pod
metadata:
  name: projected-sa-demo
  labels:
    app.kubernetes.io/name: projected-sa-demo
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v0.0.1
spec:
  containers:
  - name: main-container
    image: busybox:1.37
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:  
    - |
      echo "---Custom Service Account Token---";
      echo "[+] Token Path: /etc/service-account/token";
      echo "[+] Token content (last 20 chars):";
      cat /etc/service-account/token | tail -c -20;
      echo "";
      echo "---Default Service Account Token---";
      echo "[+] Token path: /var/run/secrets/kubernetes.io/serviceacoount/token";
      echo "[+] Token content (last 20 chars):";
      cat /var/run/secrets/kubernetes.io/serviceaccount/token | tail -c -20;
      echo "";
      sleep infinity;
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: custom-token
      mountPath: /etc/service-account
      readOnly: true # рекомендуется для projected томов
  volumes:
  - name: custom-token
    projected:
      sources:
        - serviceAccountToken:
            path: token # Имя файла для ткоена
            expirationSeconds: 3600 # Срок действия 1 час
            audience: "api-gateway" # Аудитория, для которой предназначен токен
  restartPolicy: Never
