---
apiVersion: v1
kind: Pod
metadata:
  name: downward-api-dynamic-demo
  labels:
    app.kubernetes.io/name: downward-api-dynamic-demo
    status: pending
spec:
  containers:
  - name: main-container
    image: busybox:1.37
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "---";
        echo "Readin labels at $(date): ";
        cat /etc/podinfo/labels;
        sleep 10;
      done
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
  restartPolicy: Never
