---
apiVersion: v1
kind: Pod
metadata:
  name: downward-api-volume-demo
  labels:
    app.kubernetes.io/name: downward-volume-demo
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: v0.0.1
  annotations:
    author: "Artiom Rogov"
spec:
  containers:
  - name: main-container
    image: busybox:1.37
    command:
    - sh
    - -c
    args:
    - |
      echo "---";
      echo "Pod name: $(cat /etc/podinfo/pod_name)";
      echo "Pod namespace: $(cat /etc/podinfo/pod_namespace)";
      echo "Labels: $(cat /etc/podinfo/labels)";
      echo "Annotations: $(cat /etc/podinfo/annotations)"
      echo "CPU limits: $(cat /etc/podinfo/cpu_limit)"
      echo "Memory limit: $(cat /etc/podinfo/memory_limit)"
      sleep infinity
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
        # Pod fields
        - path: "pod_name"
          fieldRef:
            fieldPath: metadata.name
        - path: "pod_namespace"
          fieldRef:
            fieldPath: metadata.namespace
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
        # Container fiels
        - path: "cpu_limit"
          resourceFieldRef:
            containerName: main-container
            resource: limits.cpu
            divisor: "1"
        - path: "memory_limit"
          resourceFieldRef:
            containerName: main-container
            resource: limits.memory
            divisor: 1Mi
  restartPolicy: Never

