---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    volumeMounts:
    - name: memory-storage
      mountPath: /tmp/memory-data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
  - name: memory-storage
    emptyDir:
      medium: Memory