---
apiVersion: v1
kind: Pod
metadata:
  name: my-sized-pod
  labels:
    app.kubernetes.io/name: my-sized-pod
spec:
  containers:
  - name: myapp
    image: busybox
    volumeMounts:
    - name: data-storage
      mountPath: /data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
  - name: data-storage
    emptyDir:
      sizeLimit: "200Mi"