---
apiVersion: v1
kind: Pod
metadata:
  name: final-pod
  namespace: work
  labels:
    app: nginx
    version: 1.27.5
spec:
  containers:
  - name: nginx-container
    image: nginx:1.27.5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
      - containerPort: 80
